/**
 * dex 트랙 전용 목(mock) 데이터.
 *
 * ⚠️ 이건 **UI 개발용 임시 데이터**입니다. 실제 데이터는 `src/data/`에서 옵니다
 *    (다른 트랙이 작업 중 — 여기서 import 하지 않습니다).
 *
 * ⚠️ 생태 정보 검증 상태: content/oncheoncheon-draft.md §3과 동일하게 **미검증**입니다.
 *    "온천천에 실제로 사는가"를 확인하지 않았습니다. 생태 자문 전에는 화면 확인 용도로만 쓰세요.
 *    (PLAN.md §11 — 서식종 목록 불일치는 도감 전체의 신뢰를 무너뜨리는 실패 모드)
 */

import type { DexEntry, Species } from '../../types/domain';

const YEAR_ROUND = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];

/** m..n 월 배열 (겨울처럼 해를 넘기는 구간도 지원: months(11, 3)) */
function months(from: number, to: number): number[] {
  const out: number[] = [];
  let m = from;
  for (let i = 0; i < 12; i += 1) {
    out.push(m);
    if (m === to) break;
    m = (m % 12) + 1;
  }
  return out.sort((a, b) => a - b);
}

export const MOCK_SPECIES: Species[] = [
  // ─── 물새 (도전 트랙) ────────────────────────────────────────
  {
    id: 'sp-mallard-spot',
    code: 'spotbill_duck',
    commonName: '흰뺨검둥오리',
    scientificName: 'Anas zonorhyncha',
    category: 'waterbird',
    tier: 1,
    track: 'challenge',
    waterGrade: null,
    months: YEAR_ROUND,
    idHint: '뺨이 하얗고 부리 끝이 노란 오리. 사계절 내내 볼 수 있어.',
    fact: '온천천에서 가장 자주 만나는 오리야. 물속에 머리를 넣고 엉덩이만 내민 채 밥을 먹기도 해.',
    ethicsFlag: 'none',
  },
  {
    id: 'sp-mallard',
    code: 'mallard',
    commonName: '청둥오리',
    scientificName: 'Anas platyrhynchos',
    category: 'waterbird',
    tier: 1,
    track: 'challenge',
    waterGrade: null,
    months: months(11, 3),
    idHint: '수컷은 머리가 초록빛으로 반짝여. 겨울에 오는 손님이야.',
    fact: '추운 북쪽에서 겨울을 나러 내려와. 봄이 되면 다시 북쪽으로 돌아가.',
    ethicsFlag: 'none',
  },
  {
    id: 'sp-great-egret',
    code: 'great_egret',
    commonName: '중대백로',
    scientificName: 'Ardea alba',
    category: 'waterbird',
    tier: 2,
    track: 'challenge',
    waterGrade: null,
    months: months(4, 10),
    idHint: '하얗고 커. 부리가 노란색이야(여름엔 검게 변해).',
    fact: '얕은 물에 꼼짝 않고 서 있다가 순식간에 부리로 물고기를 잡아. 기다림의 명수야.',
    ethicsFlag: 'no_approach',
  },
  {
    id: 'sp-little-egret',
    code: 'little_egret',
    commonName: '쇠백로',
    scientificName: 'Egretta garzetta',
    category: 'waterbird',
    tier: 2,
    track: 'challenge',
    waterGrade: null,
    months: months(4, 10),
    idHint: '하얗고 작아. 부리는 검고 발가락이 노래 — 노란 양말을 신은 것 같아!',
    fact: '중대백로와 헷갈리기 쉬운데, 발가락 색을 보면 바로 알 수 있어.',
    ethicsFlag: 'no_approach',
  },
  {
    id: 'sp-grey-heron',
    code: 'grey_heron',
    commonName: '왜가리',
    scientificName: 'Ardea cinerea',
    category: 'waterbird',
    tier: 2,
    track: 'challenge',
    waterGrade: null,
    months: YEAR_ROUND,
    idHint: '회색빛이고 백로보다 커. 목을 S자로 접고 서 있어.',
    fact: '우리나라 물가에서 가장 큰 새 가운데 하나야. 날 때도 목을 S자로 접고 날아.',
    ethicsFlag: 'no_approach',
  },
  {
    id: 'sp-cormorant',
    code: 'great_cormorant',
    commonName: '민물가마우지',
    scientificName: 'Phalacrocorax carbo',
    category: 'waterbird',
    tier: 2,
    track: 'challenge',
    waterGrade: null,
    months: months(10, 4),
    idHint: '검고 목이 길어. 날개를 활짝 펴서 말리는 자세가 특징이야.',
    fact: '물속으로 잠수해서 물고기를 쫓아가 잡아. 깃털에 기름이 적어서 젖으면 말려야 해.',
    ethicsFlag: 'none',
  },

  // ─── 작은 새 (도전 트랙) ─────────────────────────────────────
  {
    id: 'sp-sparrow',
    code: 'tree_sparrow',
    commonName: '참새',
    scientificName: 'Passer montanus',
    category: 'smallbird',
    tier: 1,
    track: 'challenge',
    waterGrade: null,
    months: YEAR_ROUND,
    idHint: '뺨에 검은 점이 하나씩 있어.',
    fact: '가장 가까이 사는 새지만, 자세히 본 적은 별로 없지? 오늘 제대로 봐줘.',
    ethicsFlag: 'none',
  },
  {
    id: 'sp-brown-eared-bulbul',
    code: 'brown_eared_bulbul',
    commonName: '직박구리',
    scientificName: 'Hypsipetes amaurotis',
    category: 'smallbird',
    tier: 1,
    track: 'challenge',
    waterGrade: null,
    months: YEAR_ROUND,
    idHint: '회갈색이고, "삐이익" 하고 시끄럽게 울며 날아가.',
    fact: '소리로 먼저 알아채는 새야. 눈으로 찾기 전에 귀로 찾아봐.',
    ethicsFlag: 'none',
  },
  {
    id: 'sp-daurian-redstart',
    code: 'daurian_redstart',
    commonName: '딱새',
    scientificName: 'Phoenicurus auroreus',
    category: 'smallbird',
    tier: 2,
    track: 'challenge',
    waterGrade: null,
    months: months(10, 4),
    idHint: '수컷은 배가 주황색이고 날개에 흰 점이 있어.',
    fact: '"딱, 딱" 하는 소리를 내서 딱새야. 이름이 소리에서 왔어.',
    ethicsFlag: 'none',
  },
  {
    id: 'sp-white-wagtail',
    code: 'white_wagtail',
    commonName: '알락할미새',
    scientificName: 'Motacilla alba',
    category: 'smallbird',
    tier: 2,
    track: 'challenge',
    waterGrade: null,
    months: months(3, 10),
    idHint: '흑백 무늬에, 꼬리를 위아래로 까딱까딱 흔들어.',
    fact: '땅 위를 종종 걸어 다니며 벌레를 잡아. 꼬리 흔들기를 멈추지 않아.',
    ethicsFlag: 'none',
  },
  {
    id: 'sp-kingfisher',
    code: 'common_kingfisher',
    commonName: '물총새',
    scientificName: 'Alcedo atthis',
    category: 'smallbird',
    tier: 4,
    track: 'challenge',
    waterGrade: null,
    months: months(4, 9),
    idHint: '등은 파랗고 배는 주황색. 물가를 쏜살같이 스쳐 지나가.',
    fact: '물 위를 총알처럼 날아 물고기를 낚아채. 만나면 정말 운이 좋은 거야!',
    ethicsFlag: 'no_approach',
  },

  // ─── 물고기 (도전 트랙) ──────────────────────────────────────
  {
    id: 'sp-carp',
    code: 'common_carp',
    commonName: '잉어',
    scientificName: 'Cyprinus carpio',
    category: 'fish',
    tier: 1,
    track: 'challenge',
    waterGrade: null,
    months: months(4, 10),
    idHint: '크고 통통해. 입가에 수염이 있어.',
    fact: '오래 사는 물고기야. 다리 위에서 내려다보면 큰 그림자처럼 보여.',
    ethicsFlag: 'none',
  },
  {
    id: 'sp-crucian-carp',
    code: 'crucian_carp',
    commonName: '붕어',
    scientificName: 'Carassius auratus',
    category: 'fish',
    tier: 1,
    track: 'challenge',
    waterGrade: null,
    months: months(4, 10),
    idHint: '잉어와 비슷하지만 수염이 없어. 수염을 찾아봐!',
    fact: '느리게 흐르는 곳을 좋아해. 잉어보다 몸이 조금 납작해.',
    ethicsFlag: 'none',
  },
  {
    id: 'sp-pale-chub',
    code: 'pale_chub',
    commonName: '피라미',
    scientificName: 'Zacco platypus',
    category: 'fish',
    tier: 2,
    track: 'challenge',
    waterGrade: 2,
    months: months(5, 10),
    idHint: '손바닥보다 작고 은빛이야. 여울에서 무리지어 다녀.',
    fact: '물이 어느 정도 맑아야 사는 물고기야. 피라미가 있으면 물이 괜찮다는 뜻!',
    ethicsFlag: 'none',
  },
  {
    id: 'sp-korean-chub',
    code: 'korean_chub',
    commonName: '갈겨니',
    scientificName: 'Nipponocypris temminckii',
    category: 'fish',
    tier: 2,
    track: 'challenge',
    waterGrade: 2,
    months: months(5, 10),
    idHint: '피라미와 비슷한데, 눈 위쪽이 붉어.',
    fact: '피라미보다 조금 더 맑은 물을 좋아해. 둘이 같이 사는 곳도 많아.',
    ethicsFlag: 'none',
  },
  {
    id: 'sp-chinese-minnow',
    code: 'chinese_minnow',
    commonName: '버들치',
    scientificName: 'Rhynchocypris oxycephalus',
    category: 'fish',
    tier: 3,
    track: 'challenge',
    waterGrade: 1,
    months: months(4, 10),
    idHint: '작고 갈색이야. 상류의 맑고 찬 물에서만 살아.',
    fact: '버들치가 사는 물은 아주 맑은 물이야. 상류에서 눈여겨봐.',
    ethicsFlag: 'none',
  },
  {
    id: 'sp-mullet',
    code: 'flathead_mullet',
    commonName: '숭어',
    scientificName: 'Mugil cephalus',
    category: 'fish',
    tier: 2,
    track: 'challenge',
    waterGrade: null,
    months: months(4, 10),
    idHint: '하류와 기수역에 살아. 가끔 물 위로 펄쩍 튀어올라!',
    fact: '민물과 바닷물이 섞이는 곳을 오가는 물고기야. 바다와 강을 잇는 증거지.',
    ethicsFlag: 'none',
  },

  // ─── 물가 곤충 (도전 트랙) ───────────────────────────────────
  {
    id: 'sp-water-strider',
    code: 'water_strider',
    commonName: '소금쟁이',
    scientificName: 'Aquarius paludum',
    category: 'insect',
    tier: 1,
    track: 'challenge',
    waterGrade: null,
    months: months(4, 10),
    idHint: '물 위를 미끄러지듯 걸어다녀.',
    fact: '다리 끝의 잔털이 물을 밀어내서 가라앉지 않아. 물의 표면장력을 타는 거야.',
    ethicsFlag: 'none',
  },
  {
    id: 'sp-skimmer',
    code: 'white_tailed_skimmer',
    commonName: '밀잠자리',
    scientificName: 'Orthetrum albistylum',
    category: 'insect',
    tier: 1,
    track: 'challenge',
    waterGrade: null,
    months: months(5, 9),
    idHint: '몸이 하늘색 가루를 뿌린 것처럼 보여.',
    fact: '잠자리는 어릴 때 물속에서 살아. 물이 있어야 잠자리도 있는 거야.',
    ethicsFlag: 'none',
  },
  {
    id: 'sp-demoiselle',
    code: 'calopteryx',
    commonName: '물잠자리',
    scientificName: 'Calopteryx japonica',
    category: 'insect',
    tier: 3,
    track: 'challenge',
    waterGrade: 1,
    months: months(5, 8),
    idHint: '날개 전체가 까맣고 몸이 금속처럼 반짝이는 초록색이야.',
    fact: '맑은 물가에서만 만날 수 있어. 나풀나풀 나비처럼 날아.',
    ethicsFlag: 'none',
  },

  // ─── 물속 바닥 친구 (도전 트랙 · 지표생물) ────────────────────
  {
    id: 'sp-melania',
    code: 'melania_snail',
    commonName: '다슬기',
    scientificName: 'Semisulcospira libertina',
    category: 'benthos',
    tier: 2,
    track: 'challenge',
    waterGrade: 2,
    months: months(4, 10),
    idHint: '뾰족한 원뿔 모양. 물속 돌에 붙어 있어.',
    fact: '돌에 붙은 이끼를 갉아 먹으며 물을 깨끗하게 해줘. 2급수를 알려주는 친구야.',
    ethicsFlag: 'none',
  },
  {
    id: 'sp-pond-snail',
    code: 'pond_snail',
    commonName: '물달팽이',
    scientificName: 'Radix auricularia',
    category: 'benthos',
    tier: 2,
    track: 'challenge',
    waterGrade: 2,
    months: months(4, 10),
    idHint: '둥글둥글한 껍데기. 물풀에 붙어 있어.',
    fact: '다슬기보다 껍데기가 둥글고 얇아. 물풀 위를 천천히 기어다녀.',
    ethicsFlag: 'none',
  },
  {
    id: 'sp-mayfly',
    code: 'mayfly',
    commonName: '하루살이',
    scientificName: 'Ephemeroptera',
    category: 'benthos',
    tier: 2,
    track: 'challenge',
    waterGrade: 2,
    months: months(4, 9),
    idHint: '꼬리가 2~3가닥으로 길게 나와 있어.',
    fact: '물속에서는 1년 넘게 살다가, 어른이 되면 며칠만 살아. 그래서 하루살이야.',
    ethicsFlag: 'none',
  },
  {
    id: 'sp-gammarus',
    code: 'gammarus',
    commonName: '옆새우',
    scientificName: 'Gammarus sp.',
    category: 'benthos',
    tier: 3,
    track: 'challenge',
    waterGrade: 1,
    months: YEAR_ROUND,
    idHint: '옆으로 누워서 헤엄쳐. 새우처럼 생겼지만 아주 작아.',
    fact: '아주 맑은 물(1급수)에서만 사는 대표 친구야. 옆새우가 있으면 물이 정말 맑다는 뜻!',
    ethicsFlag: 'expert_only',
  },
  {
    id: 'sp-planaria',
    code: 'planaria',
    commonName: '플라나리아',
    scientificName: 'Dugesia japonica',
    category: 'benthos',
    tier: 3,
    track: 'challenge',
    waterGrade: 1,
    months: YEAR_ROUND,
    idHint: '납작하고, 눈이 사시처럼 두 개 있어.',
    fact: '몸이 잘려도 다시 자라는 놀라운 친구야. 아주 맑은 물에서만 살아.',
    ethicsFlag: 'expert_only',
  },
  {
    id: 'sp-caddisfly',
    code: 'caddisfly',
    commonName: '날도래',
    scientificName: 'Trichoptera',
    category: 'benthos',
    tier: 3,
    track: 'challenge',
    waterGrade: 1,
    months: YEAR_ROUND,
    idHint: '모래알과 나뭇조각으로 집을 지어서 들고 다녀.',
    fact: '스스로 집을 만들어 사는 애벌레야. 1급수를 알려주는 친구!',
    ethicsFlag: 'expert_only',
  },

  // ─── 물가 식물 (보장 트랙) ───────────────────────────────────
  {
    id: 'sp-reed',
    code: 'reed',
    commonName: '갈대',
    scientificName: 'Phragmites australis',
    category: 'plant',
    tier: 1,
    track: 'guaranteed',
    waterGrade: null,
    months: months(8, 11),
    idHint: '키가 사람보다 크고, 끝에 부드러운 빗자루 모양 이삭이 달려.',
    fact: '뿌리가 물을 걸러줘서 하천을 깨끗하게 해. 새들이 숨는 집이기도 해.',
    ethicsFlag: 'none',
  },
  {
    id: 'sp-silver-grass',
    code: 'amur_silver_grass',
    commonName: '물억새',
    scientificName: 'Miscanthus sacchariflorus',
    category: 'plant',
    tier: 1,
    track: 'guaranteed',
    waterGrade: null,
    months: months(9, 11),
    idHint: '갈대와 비슷한데 이삭이 더 하얗고 은빛으로 빛나.',
    fact: '가을 햇빛에 은빛으로 반짝여. 갈대와 나란히 자라는 곳이 많아.',
    ethicsFlag: 'none',
  },
  {
    id: 'sp-runner-reed',
    code: 'runner_reed',
    commonName: '달뿌리풀',
    scientificName: 'Phragmites japonicus',
    category: 'plant',
    tier: 1,
    track: 'guaranteed',
    waterGrade: null,
    months: months(6, 10),
    idHint: '물가에 낮게 깔려 자라고, 줄기가 땅 위로 길게 뻗어 나가.',
    fact: '줄기가 달리듯 뻗어서 달뿌리풀이야. 상류 물가에서 자주 보여.',
    ethicsFlag: 'none',
  },
  {
    id: 'sp-persicaria',
    code: 'persicaria_thunbergii',
    commonName: '고마리',
    scientificName: 'Persicaria thunbergii',
    category: 'plant',
    tier: 1,
    track: 'guaranteed',
    waterGrade: null,
    months: months(8, 10),
    idHint: '작은 분홍·흰 꽃이 뭉쳐서 펴. 잎이 방패 모양이야.',
    fact: '더러워진 물을 걸러주는 고마운 풀이라 고마리라는 이야기도 있어.',
    ethicsFlag: 'none',
  },
  {
    id: 'sp-cattail',
    code: 'cattail',
    commonName: '부들',
    scientificName: 'Typha orientalis',
    category: 'plant',
    tier: 1,
    track: 'guaranteed',
    waterGrade: null,
    months: months(7, 10),
    idHint: '핫도그처럼 생긴 갈색 이삭! 한 번 보면 절대 안 잊어.',
    fact: '갈색 이삭이 터지면 솜털 씨앗이 바람을 타고 멀리 날아가.',
    ethicsFlag: 'none',
  },
  {
    id: 'sp-willow',
    code: 'korean_willow',
    commonName: '왕버들',
    scientificName: 'Salix chaenomeloides',
    category: 'plant',
    tier: 1,
    track: 'guaranteed',
    waterGrade: null,
    months: YEAR_ROUND,
    idHint: '물가에 서 있는 굵은 나무. 가지가 아래로 축 늘어져 있어.',
    fact: '뿌리가 흙을 붙잡아 줘서 비가 많이 와도 물가가 무너지지 않게 해줘.',
    ethicsFlag: 'none',
  },
  {
    id: 'sp-cherry',
    code: 'cherry_tree',
    commonName: '벚나무',
    scientificName: 'Prunus × yedoensis',
    category: 'plant',
    tier: 1,
    track: 'guaranteed',
    waterGrade: null,
    months: YEAR_ROUND,
    idHint: '껍질에 가로줄 무늬가 있어. 봄에는 분홍 꽃이 펴.',
    fact: '온천천 하면 벚꽃이지! 꽃이 없을 때는 껍질의 가로줄로 알아볼 수 있어.',
    ethicsFlag: 'none',
  },

  // ─── 조심할 식물 (보장 트랙) ─────────────────────────────────
  {
    id: 'sp-humulus',
    code: 'japanese_hop',
    commonName: '환삼덩굴',
    scientificName: 'Humulus scandens',
    category: 'invasive',
    tier: 1,
    track: 'guaranteed',
    waterGrade: null,
    months: months(6, 10),
    idHint: '줄기가 까끌까끌해. 다른 식물을 통째로 덮어버려.',
    fact: '너무 빨리 퍼져서 다른 풀이 햇빛을 못 받게 해. 손이 베일 수 있으니 만지지 말고 사진만 찍자.',
    ethicsFlag: 'none',
  },
  {
    id: 'sp-burcucumber',
    code: 'bur_cucumber',
    commonName: '가시박',
    scientificName: 'Sicyos angulatus',
    category: 'invasive',
    tier: 1,
    track: 'guaranteed',
    waterGrade: null,
    months: months(7, 10),
    idHint: '넓은 잎으로 나무까지 통째로 뒤덮어. 열매에 가시가 있어.',
    fact: '다른 나라에서 건너온 풀이야. 너무 잘 자라서 원래 살던 식물들이 밀려나.',
    ethicsFlag: 'none',
  },

  // ─── 남겨진 흔적 (보장 트랙) ─────────────────────────────────
  {
    id: 'sp-bird-track',
    code: 'bird_footprint',
    commonName: '새 발자국',
    category: 'trace',
    tier: 1,
    track: 'guaranteed',
    waterGrade: null,
    months: YEAR_ROUND,
    idHint: '젖은 흙이나 모래를 살펴봐. 발가락 사이에 물갈퀴 자국이 있으면 오리야!',
    fact: '새가 없어도 발자국은 남아 있어. 누가 다녀갔는지 읽어보는 것도 관찰이야.',
    ethicsFlag: 'none',
  },
  {
    id: 'sp-feather',
    code: 'feather',
    commonName: '깃털',
    category: 'trace',
    tier: 1,
    track: 'guaranteed',
    waterGrade: null,
    months: YEAR_ROUND,
    idHint: '물가에 떨어진 깃털. 줍지 말고 사진만 찍자.',
    fact: '새는 1년에 한 번씩 깃털을 갈아입어. 떨어진 깃털은 그 흔적이야.',
    ethicsFlag: 'none',
  },
  {
    id: 'sp-shell',
    code: 'empty_shell',
    commonName: '다슬기 껍데기',
    category: 'trace',
    tier: 1,
    track: 'guaranteed',
    waterGrade: null,
    months: YEAR_ROUND,
    idHint: '뾰족한 원뿔 모양의 빈 껍데기. 물가 자갈 사이를 봐.',
    fact: '껍데기가 있다는 건 여기 다슬기가 살았다는 뜻이야. 빈 껍데기도 훌륭한 증거야!',
    ethicsFlag: 'none',
  },

  // ─── 하천의 장소 (보장 트랙) ─────────────────────────────────
  {
    id: 'sp-stepping-stones',
    code: 'stepping_stones',
    commonName: '징검다리',
    category: 'facility',
    tier: 1,
    track: 'guaranteed',
    waterGrade: null,
    months: YEAR_ROUND,
    idHint: '물을 건널 수 있게 놓인 돌다리.',
    fact: '한 명씩, 뛰지 않고 건너기로 약속! 비가 온 뒤에는 미끄러워.',
    ethicsFlag: 'none',
  },
  {
    id: 'sp-riffle',
    code: 'riffle',
    commonName: '여울',
    category: 'facility',
    tier: 1,
    track: 'guaranteed',
    waterGrade: null,
    months: YEAR_ROUND,
    idHint: '물이 하얗게 부서지며 소리가 나는 얕고 빠른 곳.',
    fact: '여울에서 물에 산소가 녹아들어. 하천의 숨구멍이야. 여울이 많을수록 건강한 하천!',
    ethicsFlag: 'none',
  },
  {
    id: 'sp-water-station',
    code: 'water_quality_station',
    commonName: '수질측정소',
    category: 'facility',
    tier: 1,
    track: 'guaranteed',
    waterGrade: null,
    months: YEAR_ROUND,
    idHint: '하천 옆에 있는 작은 계기 상자나 관측 시설.',
    fact: '기계로 물의 상태를 재는 곳이야. 너는 생물로 재고, 기계는 숫자로 재는 거지.',
    ethicsFlag: 'none',
  },
  {
    id: 'sp-confluence',
    code: 'confluence',
    commonName: '합류점',
    category: 'facility',
    tier: 1,
    track: 'guaranteed',
    waterGrade: null,
    months: YEAR_ROUND,
    idHint: '두 물줄기가 만나서 하나가 되는 곳.',
    fact: '온천천은 여기서 수영강을 만나. 그리고 조금만 더 가면 바다야.',
    ethicsFlag: 'none',
  },
  {
    id: 'sp-restoration-sign',
    code: 'restoration_marker',
    commonName: '복원 기록 표지',
    category: 'facility',
    tier: 1,
    track: 'guaranteed',
    waterGrade: null,
    months: YEAR_ROUND,
    idHint: '하천을 되살린 이야기가 적힌 안내판.',
    fact: '예전엔 물이 까맣던 하천이야. 사람들이 힘을 모아 되살렸어. 오래 걸렸지만 해냈어!',
    ethicsFlag: 'none',
  },

  // ─── 특별 기록 (보호종) ──────────────────────────────────────
  // ⚠️ TODO(도메인): `SpeciesCategory`에 포유류 칸이 없어 임시로 'waterbird'에 넣었습니다.
  //    수달은 새가 아니므로 그리드에서 '물새' 섹션에 잘못 묶입니다.
  //    실제 데이터 투입 전에 domain.ts에 'mammal'을 추가할지 논의가 필요합니다.
  {
    id: 'sp-otter',
    code: 'eurasian_otter',
    commonName: '수달',
    scientificName: 'Lutra lutra',
    category: 'waterbird',
    tier: 5,
    track: 'challenge',
    waterGrade: null,
    months: YEAR_ROUND,
    idHint: '갈색 털에 통통한 몸, 굵은 꼬리. 물속을 미끄러지듯 헤엄쳐.',
    fact: '나라에서 보호하는 아주 귀한 친구야. 만나면 사진 없이 "봤어요"만 눌러줘. 절대 따라가지 않기!',
    ethicsFlag: 'report_only',
  },
];

/** 아이가 이미 획득한 카드 — 목 데이터 (12장) */
export const MOCK_ENTRIES: DexEntry[] = [
  { userId: 'u-1', speciesId: 'sp-mallard-spot', firstObservedAt: '2026-05-02T10:12:00+09:00', bestPhotoId: null, count: 4 },
  { userId: 'u-1', speciesId: 'sp-grey-heron', firstObservedAt: '2026-05-02T10:40:00+09:00', bestPhotoId: null, count: 1 },
  { userId: 'u-1', speciesId: 'sp-sparrow', firstObservedAt: '2026-04-18T09:30:00+09:00', bestPhotoId: null, count: 7 },
  { userId: 'u-1', speciesId: 'sp-carp', firstObservedAt: '2026-05-02T10:55:00+09:00', bestPhotoId: null, count: 2 },
  { userId: 'u-1', speciesId: 'sp-pale-chub', firstObservedAt: '2026-05-02T11:05:00+09:00', bestPhotoId: null, count: 1 },
  { userId: 'u-1', speciesId: 'sp-water-strider', firstObservedAt: '2026-05-02T11:12:00+09:00', bestPhotoId: null, count: 3 },
  { userId: 'u-1', speciesId: 'sp-melania', firstObservedAt: '2026-05-02T11:20:00+09:00', bestPhotoId: null, count: 2 },
  { userId: 'u-1', speciesId: 'sp-pond-snail', firstObservedAt: '2026-05-02T11:24:00+09:00', bestPhotoId: null, count: 1 },
  { userId: 'u-1', speciesId: 'sp-willow', firstObservedAt: '2026-04-18T09:45:00+09:00', bestPhotoId: null, count: 5 },
  { userId: 'u-1', speciesId: 'sp-cherry', firstObservedAt: '2026-04-18T09:50:00+09:00', bestPhotoId: null, count: 6 },
  { userId: 'u-1', speciesId: 'sp-stepping-stones', firstObservedAt: '2026-05-02T10:20:00+09:00', bestPhotoId: null, count: 1 },
  { userId: 'u-1', speciesId: 'sp-riffle', firstObservedAt: '2026-05-02T10:22:00+09:00', bestPhotoId: null, count: 1 },
];

/** 획득 연출 확인용 */
export const MOCK_ACQUIRED_SPECIES: Species =
  MOCK_SPECIES.find((s) => s.id === 'sp-melania') ?? MOCK_SPECIES[0];
